# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.23.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ["--fix"]
        additional_dependencies:
          - eslint@latest
          - "@typescript-eslint/eslint-plugin@latest"
          - "@typescript-eslint/parser@latest"
          - eslint-plugin-import@latest
          - eslint-plugin-n@latest
          - eslint-plugin-promise@latest
          - eslint-config-standard@latest
          - eslint-config-standard-ts@latest
          # and whatever other plugins...
