# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  # ESLint flat-config (ESLint 9) hook. We must pin versions and include @eslint/js + typescript-eslint
  # because the hook installs its own isolated env (it does NOT use devDependencies).
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.34.0  # keep in sync with package.json
    hooks:
      - id: eslint
        files: \.[jt]s$  # *.js and *.ts (no JSX in this repo presently)
        types: [file]
        args: ["--fix"]
        additional_dependencies:
          - eslint@9.34.0
          - '@eslint/js@9.34.0'
          - 'typescript-eslint@8.40.0'
        # If later adding plugins, list them here pinned to versions.
